"""Dropped show grid

Revision ID: 38c499cded63
Revises: bf9f0690cab4
Create Date: 2025-09-15 19:39:16.342352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c499cded63'
down_revision = 'bf9f0690cab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('show_grid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_grid', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
