"""add language to settings

Revision ID: 6d42e170aea5
Revises: ffab3e13d363
Create Date: 2026-01-05 19:12:45.003849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d42e170aea5'
down_revision = 'ffab3e13d363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), server_default='ro', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
