"""Added time slot start and end time, fee

Revision ID: 84bc5bd9acb2
Revises: ebf55ea14e01
Create Date: 2025-09-04 13:29:47.544592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84bc5bd9acb2'
down_revision = 'ebf55ea14e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_slot_start_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_slot_end_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_slot_fee', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('time_slot_fee')
        batch_op.drop_column('time_slot_end_time')
        batch_op.drop_column('time_slot_start_time')

    # ### end Alembic commands ###
