"""Added API key, secret and store url

Revision ID: 8d8216ad18e8
Revises: 
Create Date: 2025-09-15 15:48:56.571870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8216ad18e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('store_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('store_url')
        batch_op.drop_column('api_secret')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
