"""Added grid/list settings

Revision ID: bf9f0690cab4
Revises: 8d8216ad18e8
Create Date: 2025-09-15 18:50:33.914711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9f0690cab4'
down_revision = '8d8216ad18e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_grid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('show_grid')

    # ### end Alembic commands ###
