"""Added extra products check

Revision ID: d185e95223d9
Revises: e1df974fd4bd
Create Date: 2025-09-25 20:54:34.827064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd185e95223d9'
down_revision = 'e1df974fd4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_extra_products', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('show_extra_products')

    # ### end Alembic commands ###
