"""Added addons

Revision ID: e1df974fd4bd
Revises: 
Create Date: 2025-09-19 23:21:34.803292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1df974fd4bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addons', sa.JSON(), nullable=True))
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('time_slot_start_time')
        batch_op.drop_column('time_slot_fee')
        batch_op.drop_column('delivery_time_slot')
        batch_op.drop_column('time_slot_end_time')
        batch_op.drop_column('delivery_method')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addons', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('addons')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_method', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_slot_end_time', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_time_slot', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_slot_fee', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_slot_start_time', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.VARCHAR(length=12), nullable=True))
        batch_op.drop_column('addons')

    # ### end Alembic commands ###
