"""Added delivery_date & delivery_time_slot

Revision ID: ebf55ea14e01
Revises: 0cc42e09348d
Create Date: 2025-09-03 15:17:40.478722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf55ea14e01'
down_revision = '0cc42e09348d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('delivery_time_slot', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_time_slot')
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###
