"""added delivered_at field to orders

Revision ID: ffab3e13d363
Revises: df5bfd029454
Create Date: 2025-12-31 17:27:34.246099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffab3e13d363'
down_revision = 'df5bfd029454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_delivered_at'), ['delivered_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_delivered_at'))
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
